#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables
    
- name: Remove cadvisor Container
  docker_container:
    name: cadvisor
    state: absent

- name: Deploy cadvisor Container
  docker_container:
    name: cadvisor
    image: "{{ cadvisor_docker_image_name }}:{{ cadvisor_docker_version }}"
    pull: "{{ cadvisor_docker_pull_images|bool }}"
    cpu_shares: 128
    published_ports:
    - "{{ports.stdout}}{{ cadvisor_docker_expose_port }}:8080"
    command: '--logtostderr'
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    env:
      PUID: 1000
      PGID: 1000
    networks:
      - name: plexguide
        aliases:
          - cadvisor
    restart_policy: always
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:cadvisor.{{domain.stdout}}"
      traefik.port: "8082"