#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables
    
- name: Remove NZBHydra2 Container
  docker_container:
    name: nzbhydra2
    state: absent

- name: Deploy NZBHydra2 Container
  docker_container:
    name: nzbhydra2
    image: "hotio/suitarr"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}5076:5076"
    env:
      APP: "nzbhydra2"
      VERSION: "unstable"
      PUID: "1000"
      PGID: "1000"
      BACKUP: "no"
      MONO_TLS_PROVIDER: legacy
    volumes:
      - "/opt/appdata/nzbhydra2:/config"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - nzbhydra2
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:nzbhydra.{{domain.stdout}}, nzbhydra2.{{domain.stdout}}"
      traefik.port: "5076"
