---
- include_role:
    name: variables

- name: Remove uTorrent Container
  docker_container:
    name: utorrent
    state: absent

- name: Remove Previous Settings
  file:
    path: /opt/appdata/utorrent
    state: absent

- name: Deploy uTorrent Container
  docker_container:
    name: utorrent
    image: ekho/utorrent
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}8080:8080"
      - "6882:6882/udp"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /opt/appdata/utorrent/settings/utserver.conf:/utorrent/utserver.conf
      - /opt/appdata/utorrent/settings:/utorrent/settings
      - /opt/appdata/utorrent/data:/utorrent/data
      - /opt/appdata/utorrent/downloads/active:/active
      - /opt/appdata/utorrent/torrents/autoload:/autoload
      - /opt/appdata/utorrent/torrents/files:/torrents
      - /etc/localtime:/etc/localtime:ro
      - /mnt/unionfs/:/unionfs
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - utorrent
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.auth.basic: "{{auth.stdout}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:utorrent.{{domain.stdout}}"
      traefik.port: "8080"

- name: Install utserver.conf
  template:
    src: utserver.conf
    dest: /opt/appdata/utorrent/settings/utserver.conf
    force: yes
    mode: 0775
