#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: "Establishing Variable"
  shell: "awk '{print $1}' /tmp/program_var"
  register: program_var

- debug: msg="Temp Message - For {{program_var.stdout}}"

- name: "Checking {{program_var.stdout}} location in APPDATA"
  stat:
    path: /opt/appdata/{{program_var.stdout}}
  register: programappdata

- name: "Checking if RCLone Encrypted"
  stat:
    path: /var/plexguide/rclone-en.yes
  register: encrypted

- name: Stopping Docker Container - {{program_var.stdout}}
  docker_container:
    name: "{{program_var.stdout}}"
    state: stopped
  ignore_errors: True
  when: programappdata.stat.exists == True

- debug: msg="Time Length can be Long or Short! Please Wait!"
  when: programappdata.stat.exists == True

## https://stackoverflow.com/questions/45864831/ansible-how-to-delete-a-folder-and-file-inside-a-directory-in-a-single-task
- name: Remove Old Backup
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /mnt/gdrive/plexguide/backup/{{program_var.stdout}}.tar
  when: programappdata.stat.exists == True

## https://askubuntu.com/questions/553158/compressing-a-folder-tar-without-its-containing-directory-in-the-folder-name
- name: Backing Up Program to GDrive - {{program_var.stdout}}
  shell: "tar --ignore-failed-read -zcvf /tmp/{{program_var.stdout}}.tar -C /opt/appdata/{{program_var.stdout}} ."
  when: programappdata.stat.exists == True

#- name: Backing Up Program to GDrive - {{program_var.stdout}}
#  shell: "tar --exclude='./plex/database/Library/Application Support/Plex Media Server/Cache/PhotoTranscoder' --ignore-failed-read -zcvf /tmp/{{program_var.stdout}}.tar -C /opt/appdata/{{program_var.stdout}} ."
#  when: programappdata.stat.exists == True and plex.stat.exist= True

- name: Restart Docker Container - {{program_var.stdout}}
  docker_container:
    name: "{{program_var.stdout}}"
    state: started
  ignore_errors: True
  when: programappdata.stat.exists == True

- name: Uploading Backup to Google Drive
  shell: "rclone copy /tmp/{{program_var.stdout}}.tar gdrive:/plexguide/backup -v --checksum --drive-chunk-size=64M"
  when: encrypted.stat.exists == False and programappdata.stat.exists == True

- name: Uploading Backup to Google Drive (encrypted)
  shell: "rclone copy /tmp/{{program_var.stdout}}.tar gcrypt:/plexguide/backup -v --checksum --drive-chunk-size=64M"
  when: encrypted.stat.exists == True and programappdata.stat.exists == True

- name: Kill Switch
  shell: echo "false" > /tmp/alive

- debug: msg="Program is now backed up to your Google Drive - {{program_var.stdout}}"
  when: programappdata.stat.exists == True

- debug: msg="The Program's Data DOES NOT EXIST Locally - Cannot Backup {{program_var.stdout}}"
  when: programappdata.stat.exists == False
