---
- hosts: localhost

  vars_files:
    - /opt/appdata/plexguide/var-vpn.yml

## sudo ansible-playbook /opt/plexguide/ansible/config-vpn.yml # to generate the vpn var file required above
## sudo mv /opt/plexguide/scripts/menus/programs /opt/plexguide/scripts/menus/programs3
## sudo mv /opt/plexguide/scripts/menus/programs2 /opt/plexguide/scripts/menus/programs

  roles:
      - { role: rtorrentvpn, tags: ['rtorrentvpn'] }
      - { role: delugevpn, tags: ['delugevpn'] }
      - { role: x2go, tags: ['x2go'] }
      - { role: encache, tags: ['encache'] }
