#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Remove Watchtower Container
  docker_container:
    name: watchtower
    state: absent

- name: Deploy Watchtower (No Plex Emby)
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    pull: yes
    command: medusa tautulli resilio next ubooquity sickrage mylar sabnzbd alltube rutorrent netdata jackett nzbhydra nzbhydra2 nzbget organizr muximux portainer sonarr radarr watchtower ombi traefik ombi4k htpcmanager radarr4k sonarr4k traefik2 booksonic airsonic cloudcmd headphones heimdall --cleanup --interval 600
    cpu_shares: 64
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    networks:
      - name: plexguide 
        aliases:
          - watchtower
  tags: plexemby

- name: Deploy Watchtower (All)
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    pull: yes
    command: medusa ubooquity resilio next sickrage mylar plex emby netdata rutorrent sabnzbd tautulli jackett nzbhydra nzbhydra2 nzbget organizr muximux portainer sonarr radarr watchtower ombi traefik sonarr4k htpcmanager alltubeombi4k radarr4k traefik2 booksonic airsonic cloudcmd headsphones heimdall --cleanup --interval 600
    cpu_shares: 64
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - watchtower
  tags: watchall