#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables
    
- docker_container:
    name: medusa
    state: absent

- name: Create Medusa Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - "{{path.stdout}}/medusa"
    - "{{path.stdout}}/medusa/downloads"

- name: Deploy Medusa Container
  docker_container:
    name: medusa
    image: "linuxserver/medusa"
    pull: yes
    published_ports:
      - "{{ports.stdout}}8081:8081"
    volumes:
      - /opt/appdata/medusa:/config
      - /mnt/unionfs:/unionfs
      - "{{path.stdout}}/deluge/downloaded:/downloaded"
      - "{{path.stdout}}/torrentvpn/downloaded:/data/completed"
      - "{{path.stdout}}/sab/complete:/complete"
      - "{{path.stdout}}/nzbget/completed:/completed"
      - "{{path.stdout}}/rutorrents:/downloads"
      - "{{path.stdout}}/deluge/downloaded:/downloaded"
    cpu_shares: 256
    env:
      PUID: 1000
      PGID: 1000
    networks:
      - name: plexguide
        aliases:
          - medusa
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:medusa.{{domain.stdout}}"
      traefik.port: "8081"
