#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables
 
########## Unique for TLD
- name: Register TLD if it exists
  shell: "cat /var/plexguide/tld.{{ role_name }}"
  register: tld
  ignore_errors: True
##########
    
- name: Remove HTPCManager Container
  docker_container:
    name: htpcmanager
    state: absent

- name: Deploy HTPCManager Container
  docker_container:
    name: htpcmanager
    image: linuxserver/htpcmanager
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}8085:8085"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "/opt/appdata/htpcmanager:/config"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: plexguide
        aliases:
          - htpcmanager
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:htpcmanager.{{domain.stdout}}{{tld.stdout}}"
      traefik.port: "8085"
    restart_policy: always
    state: started
